In [1]:
import numpy as np
import pandas as pd
import scipy

In [2]:
#read file
file_location = "/home/sym/BA501_2Session/"
file_name = "orders_new.csv"
my_data = pd.read_csv(file_location + file_name)

In [3]:
my_data.head(5)

,country,date,experiment_id,order_id,spend_usd,user_id,vertical
0,US,2017-04-02,12624549,6720123150182430132,49.99,3659561261588336546,ANDROID_APPS
1,US,2017-04-01,12624549,17511438899767627798,0.99,3659561261588336546,ANDROID_APPS
2,US,2017-04-04,12624549,1549342062436664018,39.99,3659561261588336546,ANDROID_APPS
3,US,2017-04-04,12624549,7771425263197855716,19.99,3659561261588336546,ANDROID_APPS
4,US,2017-04-01,12624549,17943210556580942992,19.99,3659561261588336546,ANDROID_APPS

In [7]:
#How do you handle duplicate values in a dataset in Python?
#using "pandas"
#Checking for duplicates
my_data.shape

(39958, 7)

In [8]:
my_data.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
39928    False
39929    False
39930    False
39931    False
39932    False
39933    False
39934    False
39935    False
39936    False
39937    False
39938    False
39939    False
39940    False
39941    False
39942    False
39943    False
39944    False
39945    False
39946    False
39947    False
39948    False
39949    False
39950    False
39951    False
39952    False
39953    False
39954    False
39955    False
39956    False
39957    False
Length: 39958, dtype: bool

In [10]:
my_data.duplicated('country')

0        False
1         True
2         True
3         True
4         True
5         True
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19        True
20        True
21        True
22        True
23        True
24       False
25        True
26        True
27        True
28        True
29        True
         ...
39928     True
39929     True
39930     True
39931     True
39932     True
39933     True
39934     True
39935     True
39936     True
39937     True
39938     True
39939     True
39940     True
39941     True
39942     True
39943     True
39944     True
39945     True
39946     True
39947     True
39948     True
39949     True
39950     True
39951     True
39952     True
39953     True
39954     True
39955     True
39956     True
39957     True
Length: 39958, dtype: bool

In [11]:
#There is no duplicates in order table, whole table will be output
#Dropping duplicates from a particular column: df.drop_duplicates([‘col1’], keep = '')
my_data.drop_duplicates()

,country,date,experiment_id,order_id,spend_usd,user_id,vertical
0,US,2017-04-02,12624549,6720123150182430132,49.990000,3659561261588336546,ANDROID_APPS
1,US,2017-04-01,12624549,17511438899767627798,0.990000,3659561261588336546,ANDROID_APPS
2,US,2017-04-04,12624549,1549342062436664018,39.990000,3659561261588336546,ANDROID_APPS
3,US,2017-04-04,12624549,7771425263197855716,19.990000,3659561261588336546,ANDROID_APPS
4,US,2017-04-01,12624549,17943210556580942992,19.990000,3659561261588336546,ANDROID_APPS
5,US,2017-04-01,12624549,14181259234722501452,9.990000,3659561261588336546,ANDROID_APPS
6,US,2017-04-06,12624549,2216871028985838700,19.990000,3659561261588336546,ANDROID_APPS
7,US,2017-04-05,12624548,2401579091544890692,0.990000,2320465914243698778,ANDROID_APPS
8,US,2017-04-06,12624548,6311345639701552883,4.990000,14788950912323597325,ANDROID_APPS
9,US,2017-04-05,12624549,7059034589483462446,49.990000,16325981456106360689,ANDROID_APPS
10,US,2017-04-01,12624548,8047726651081695000,18.990000,12159209502669351307,YOUTUBE
11,US,2017-04-02,12624548,5603707383013558380,0.990000,12159209502669351307,ANDROID_APPS
12,US,2017-04-06,12624549,12362551400876756253,9.130000,8094820023650192121,ANDROID_APPS
13,US,2017-04-07,12624549,15059046880188771429,84.990000,15692059163785601835,ANDROID_APPS
14,US,2017-04-02,12624549,2871448946156169834,9.990000,2815189593328845113,ANDROID_APPS
15,US,2017-04-04,12624548,13459247158220046874,3.170000,16577159990095179651,ANDROID_APPS
16,US,2017-04-03,12624548,9124965139682611283,1.990000,16577159990095179651,ANDROID_APPS
17,US,2017-04-04,12624548,11809794351426657828,1.990000,16577159990095179651,ANDROID_APPS
18,US,2017-04-04,12624548,13157539199411902760,3.170000,16577159990095179651,ANDROID_APPS
19,US,2017-04-06,12624548,14490310714996236403,9.990000,7921417227562122166,ANDROID_APPS
20,US,2017-04-04,12624548,3290475667473218394,5.990000,7921417227562122166,ANDROID_APPS
21,US,2017-04-03,12624548,2363982117728400422,5.990000,7921417227562122166,ANDROID_APPS
22,US,2017-04-03,12624548,3672971965948827775,5.990000,7921417227562122166,ANDROID_APPS
23,US,2017-04-01,12624548,1413913652881772607,5.990000,7921417227562122166,ANDROID_APPS
24,JP,2017-04-05,12624548,2525826418438548739,4.330404,4743896920079121512,ANDROID_APPS
25,JP,2017-04-07,12624548,3441295522770636935,8.656727,4743896920079121512,ANDROID_APPS
26,JP,2017-04-02,12624548,2185804523050628545,4.617505,4743896920079121512,ANDROID_APPS
27,JP,2017-04-02,12624548,6572076828771982860,4.303694,4743896920079121512,ANDROID_APPS
28,JP,2017-04-01,12624549,186226775422147605,2.904994,8260905743282750841,ANDROID_APPS
29,JP,2017-04-04,12624549,870018612952843897,10.847502,8260905743282750841,ANDROID_APPS
...,...,...,...,...,...,...,...
39928,US,2017-04-03,12624548,5821164112214003719,19.990000,10679177434875081346,ANDROID_APPS
39929,US,2017-04-06,12624548,11589457450852347494,1.370000,9539313523556304429,MUSIC
39930,US,2017-04-06,12624548,219751666395282743,1.370000,9539313523556304429,MUSIC
39931,US,2017-04-06,12624548,11297322713795535170,1.370000,9539313523556304429,MUSIC
39932,JP,2017-04-07,12624548,12273337848020842448,7.033591,4681279655220540349,MUSIC
39933,JP,2017-04-06,12624549,1385083079209127792,43.323170,1094405757232853283,ANDROID_APPS
39934,JP,2017-04-06,12624549,3021406282412935465,21.661585,1094405757232853283,ANDROID_APPS
39935,JP,2017-04-02,12624549,13736612604962710703,5.379618,1094405757232853283,ANDROID_APPS
39936,JP,2017-04-06,12624549,10135803440975060907,10.830792,1094405757232853283,ANDROID_APPS
39937,JP,2017-04-05,12624549,4732273272676544742,21.652020,1094405757232853283,ANDROID_APPS
39938,JP,2017-04-05,12624549,16814935216672287168,21.652020,1094405757232853283,ANDROID_APPS
39939,JP,2017-04-05,12624549,11381770963406163958,21.652020,1094405757232853283,ANDROID_APPS
39940,JP,2017-04-05,12624549,14003660076146318358,21.652020,1094405757232853283,ANDROID_APPS
39941,JP,2017-04-06,12624549,5788309374151439281,10.830792,1094405757232853283,ANDROID_APPS
39942,JP,2017-04-06,12624549,8537227085867618881,5.415396,1094405757232853283,ANDROID_APPS
39943,JP,2017-04-07,12624549,17931161425223479298,88.370760,1094405757232853283,ANDROID_APPS
39944,JP,2017-04-06,12624549,15529246781976257719,5.415396,1094405757232853283,ANDROID_APPS
39945,JP,2017-04-06,12624549,16098942353087732386,5.415396,1094405757232853283,ANDROID_APPS
39946,JP,2017-04-04,12624549,12902114681662395386,5.423751,1094405757232853283,ANDROID_APPS
39947,JP,2017-04-06,12624549,9292545309188203104,10.830792,1094405757232853283,ANDROID_APPS
39948,JP,2017-04-03,12624549,4924303018725488789,5.401230,1094405757232853283,ANDROID_APPS
39949,JP,2017-04-06,12624549,6027165513553076715,21.661585,1094405757232853283,ANDROID_APPS
39950,JP,2017-04-07,12624548,10831227652271248247,6.490611,5547486050352513671,ANDROID_APPS
39951,US,2017-04-06,12624549,2288349597257767937,4.310000,5874252743493795322,YOUTUBE
39952,US,2017-04-05,12624548,10624753443143470907,1.990000,357840552758620390,ANDROID_APPS
39953,US,2017-04-04,12624549,9305375196309306561,9.990000,4489579059658865688,ANDROID_APPS
39954,US,2017-04-01,12624548,10864021731086048938,9.990000,12984055359496400963,ANDROID_APPS
39955,US,2017-04-07,12624548,11896472227391290390,9.990000,12984055359496400963,ANDROID_APPS
39956,US,2017-04-04,12624548,12777924912899351064,9.990000,12984055359496400963,ANDROID_APPS
39957,US,2017-04-03,12624548,3178547077051994619,14.990000,2697241628661480461,MUSIC